---
#
# Ansible managed
#
repository:
  description: Install and configure logrotate on your system.
  homepage: https://buluma.co.ke/
  topics: logrotate, ansible, molecule, tox, playbook, hacktoberfest
