---

- name: test if logrotate_frequency is set correctly
  ansible.builtin.assert:
    that:
      - logrotate_frequency is defined
      - logrotate_frequency is string
      - logrotate_frequency in [ "daily", "weekly", "monthly" ]
    quiet: yes

- name: test if logrotate_keep is set correctly
  ansible.builtin.assert:
    that:
      - logrotate_keep is defined
      - logrotate_keep is number
      - logrotate_keep >= 0
    quiet: yes

- name: test if logrotate_compress is set correctly
  ansible.builtin.assert:
    that:
      - logrotate_compress is defined
      - logrotate_compress is boolean
    quiet: yes

- name: test if logrotate_user is set correctly
  ansible.builtin.assert:
    that:
      - logrotate_user is defined
      - logrotate_user is string
    quiet: yes

- name: test if logrotate_group is set correctly
  ansible.builtin.assert:
    that:
      - logrotate_group is defined
      - logrotate_group is string
    quiet: yes
